name = "aiken-extra/fuzz_util"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "An Aiken utility library containing various fuzzers"

[repository]
user = "aiken-extra"
project = "fuzz_util"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "2.1.0"
source = "github"

[config]
